ccflags-y += -Werror $(call cc-disable-warning, format)
# Host MHI stack
obj-y += host/

# Endpoint MHI stack
obj-y += ep/

# MHI Devices stack
obj-y += devices/

#MHI Controller stack
obj-y += controllers/
